### PR TITLE
Events

### PR DESCRIPTION
**Pull request by jaruba**
Basic usage:

```
multipass = require('multipass-torrent/cli/multipass');

multipass.onBuffering(function(source,perc) {
    console.log("Source: "+source);
    console.log("Percent: "+perc);
});

multipass.onFinished(function(source) {
    console.log("Finished with Source: "+source);
});

multipass.onFound(function(source,torrent) {
    console.log("Found Torrent:");
    console.log(torrent);
});

multipass.importQueue.push("https://kat.cr/usearch/2015/2/");
```

`source` is the url it is parsing, this is emitted with the events in order to distinguish between the progress / torrents of various pages that are being processed in parallel.

### CODE REVIEW

**Comment by Ivshti** [comment]
I'll make a few changes and then merge - instead of events_mod, just use events - the event emitter would be mp.events (mp being module.exports) and instead of various .onStuff functions you could just use mp.events.on()

Or even simpler, init MP as an EventEmitter, and then extend it with everything exported.
Then you can just do mp.on("buffering")

I'll take a look tomorrow morning

**Comment by jaruba** [comment]
Ha! had a feeling you wouldn't like my jquery-like events :))

> Or even simpler, init MP as an EventEmitter, and then extend it with everything exported.

Thought didn't cross my mind, it sounds like the cleanest solution.

**Comment by jaruba** [comment]
Also (although this is not really important), my jquery-like events have the added advantage of method chaining (ie: `multipass.onFound(...).onBuffering(...).onFinished(...)`)

**Comment by Ivshti** [comment]
EventEmitter supports that too. You can still .on("..").on("..")

**Comment by jaruba** [comment]
(did not know that, [sometimes i like to dig a hole in my back yard and pretend i'm a carrot](https://www.facebook.com/pages/Sometimes-i-Like-to-dig-a-hole-in-my-back-yard-and-pretend-im-a-carrot/207778429328614))

**Comment by jaruba** [comment]
Simplified, events can now be used in the form of:

```
mp = require('multipass-torrent/cli/multipass');

mp.on("Buffering",function(source,perc) {
    console.log("Source: "+source);
    console.log("Percent: "+perc);
});

mp.on("Finished",function(source) {
    console.log("Finished with Source: "+source);
});

mp.on("Found",function(source,torrent) {
    console.log("Found Torrent:");
    console.log(torrent);
});

mp.importQueue.push("https://kat.cr/usearch/2015/2/");
```

**Comment by Ivshti** [comment]
Merged, thanks @jaruba

**Comment by jaruba** [comment]
I thought this moment will never come.. :))

**Comment by Ivshti** [comment]
I wanted to do some refactoring to simplify the API, but it's not going to be today

what do we say to the refactoring when we're swamped -> http://i1012.photobucket.com/albums/af244/FiercelyNormal/Not-today-1.gif

**Pull request merged**
